### ISSUE TITLE
0.0.4 contains jupyter_telemetry/sphinxext

### ISSUE THREAD

**Issue by minrk** [jupyter/telemetry#37]
The 0.0.4 release includes a `jupyter_telemetry.sphinxext` subpackage not in the repo, which appears incomplete.

My guess is these were some uncommitted working files? It can be a good idea to try `git status` before making a release, and `git clean -xfd` can delete any files in the repo not tracked prior to making a release (commit/stash first if you have untracked files that you want to keep!).

Automatically publishing releases from CI, as we are exploring doing across JupyterHub repos, can also avoid issues like this.

**Comment by Zsailer** [comment]
Thanks, @minrk. That was my fault—just some sloppy when doing a release on my end. Sorry about that. 

I've opened #39 with a Sphinx extension for telemetry. Let's quickly get that merged and cut a new release the proper way.

**Comment by Zsailer** [comment]
> Automatically publishing releases from CI, as we are exploring doing across JupyterHub repos, can also avoid issues like this.

This looks cool. It would certainly help save time, too. I find that making releases is time-consuming.

**Comment by Zsailer** [comment]
Released a 0.0.5 that fixes this issue. Again, sorry for the trouble this created.
