### ISSUE TITLE
More descriptive intro paragraph in README

### ISSUE THREAD

**Issue by consideRatio** [jupyter/telemetry#38]
I've come to greatly appreciate very reader friendly introduction paragraphs in README files. It help to introduce those that doesn't already is looking for exactly what a project provides and knows various use cases of a project ahead of time.

Here is my best attempt to describe the [jupyterhub/traefik-proxy](https://github.com/jupyterhub/traefik-proxy) in the README as an example of what I mean. It will have some understanding assumptions within it still, such as what a proxy is, but there could had been a lot more assumptions made in it also.

> When JupyterHub starts a server for a user, it will _dynamically configure a proxy server_ so that accessing `jupyterhub.example.com/user/<user>` routes to the individual Jupyter server. This project contains what JupyterHub need to dynamically configure the routes of a [traefik](https://traefik.io) proxy server! There are three implementations of the [JupyterHub proxy API](https://jupyterhub.readthedocs.io/en/stable/reference/proxy.html), depending on how traefik store its routing configuration.

For the jupyter_telemetry project, I would benefit from an explanation of what telemetry is, it is a somewhat complicated word that I ended up googling.

> telemetry: the process of recording and transmitting the readings of an instrument.

So perhaps the leading paragraph of the README could describe that, and describe how that maps to what jupyter_telemetry provides. My understanding is that it is used to provide an API to record events with schema validation, and that the transmitting part is pluggable by a handler - and the handler could be to write to a file but perhaps also to make a web request for example.

## Question
Is my understanding about right and does it give a complete picture?

**Comment by Zsailer** [comment]
@consideRatio Great idea! Check out #40. I'd love to get your feedback on making that summary paragraph useful and interpretable.

**Comment by Zsailer** [comment]
Addressed in #40.
