### ISSUE TITLE
EventLog is using a shared logger instance

### ISSUE THREAD

**Issue by blink1073** [jupyter/telemetry#44]
If multiple packages instantiate `EventLog`, they end up sharing the same [logger](https://github.com/jupyter/telemetry/blob/ede6d17312cd57fe1441dc1222280834ca3d6f03/jupyter_telemetry/eventlog.py#L59), meaning they write to each other's handlers.  We should ensure a unique logger for each instance of `EventLog`.

**Comment by blink1073** [comment]
If we use `logging.getLogger(f'{__name__}.{id(self)}')` the it will be guaranteed to be unique.  The logs are structured, so the hash won't show up anywhere.

**Comment by Zsailer** [comment]
Good catch, @blink1073! And thanks for the fix!
