### ISSUE TITLE
Final review of JEP

### ISSUE THREAD

**Issue by Zsailer** [jupyter/telemetry#5]
I'm going to do a final review of the documentation today (mostly to standardize `emit` vs. `record_event` in places), then I think we should submit this JEP to `jupyter/enhancement-proposals` tomorrow. Any objections? @jaipreet-s @yuvipanda

**Comment by jaipreet-s** [comment]
Sorry for the late reply. No objections! I'm actually in favor to just post the JEP as-is with some quick fixes and iterate. We're going to get feedback regardless.

**Comment by Zsailer** [comment]
Ok that's fine with me! You want to go ahead and submit the PR?

**Comment by jaipreet-s** [comment]
Done, finally https://github.com/jupyter/enhancement-proposals/pull/41

Are you able to push commits to my fork to address feedback or make changes? If not, let me know and I'll configure permissions accordingly.

**Comment by Zsailer** [comment]
Great, thanks @jaipreet-s! I'll let you know if/when I run into issues pushing commits to your fork.

**Comment by jaipreet-s** [comment]
I've invited @Zsailer  and @yuvipanda as "Collaborators" on my fork so you should be able to push. Let me know if there's another preferred way or the permissions aren't pushed. Additionally, I've @ tagged you guys on some of the feedback in the JEP.
