### ISSUE TITLE
Public Meeting on Telemetry

### ISSUE THREAD

**Issue by Zsailer** [jupyter/telemetry#53]
Hey all, 

A few of us are planning to meet on Tuesday, September 8th, 2020 at 8am Pacific (or [your timezone](https://arewemeetingyet.com/Los%20Angeles/2020-09-08/08:00/Telemetry%20Meeting#eyJ1cmwiOiJodHRwczovL2NhbHBvbHkuem9vbS51cy9teS96c2FpbGVyIn0= )) to discuss a few things around Jupyter Telemetry.
* JupyterCon Talk
* Fine grained telemetry PR #49 
* Telemetry in Jupyter Server: jupyter/jupyter_server#233
* Future direction

Let's meet in the [my Zoom Channel](https://calpoly.zoom.us/my/zsailer).

**Comment by yuvipanda** [comment]
Unfortunately I've to do some medical things tonight and so won't be able to make this :'( Sorry guys!
